GET http://localhost:5102/games

###
GET http://localhost:5102/games/1

###
POST http://localhost:5102/games
Content-Type: application/json

{
    "name": "The Legend of Zelda: Breath of the Wild",
    "genreId": 1,
    "price": 59.99,
    "releaseDate": "2017-03-03"
}